In [3]:
import numpy as np
import pandas as pd

In [4]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [12]:
print(f"X shape: {x_train.shape}, X type:{type(x_train)}")
print(f"Square Feet, Numbers of bedroom, Numbers of floor, Age of home")
print(x_train)
print(f"Y shape: {y_train.shape}, Y type:{type(y_train)}")
print(f"Price")
print(y_train)

X shape: (3, 4), X type:<class 'numpy.ndarray'>
Square Feet, Numbers of bedroom, Numbers of floor, Age of home
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y shape: (3,), Y type:<class 'numpy.ndarray'>
Price
[460 232 178]


In [13]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>
