In [1]:
import numpy as np
import pandas as pd

In [2]:
x_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [3]:
print(f"X shape: {x_train.shape}, X type:{type(x_train)}")
print(f"Square Feet, Numbers of bedroom, Numbers of floor, Age of home")
print(x_train)
print(f"Y shape: {y_train.shape}, Y type:{type(y_train)}")
print(f"Price")
print(y_train)

X shape: (3, 4), X type:<class 'numpy.ndarray'>
Square Feet, Numbers of bedroom, Numbers of floor, Age of home
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
Y shape: (3,), Y type:<class 'numpy.ndarray'>
Price
[460 232 178]


In [4]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [5]:
# Vector dot product for single column or features

def predict_single_loop(x, w, b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [8]:
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
print(f"w: {w_init}");
print(f"b_init: {b_init}");
# make a prediction
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, predcition: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
w: [  0.39133535  18.75376741 -53.36032453 -26.42131618]
b_init: 785.1811367994083
f_wb shape (), predcition: 459.9999976194083


In [7]:
def predict(x, w, b):
    p = np.dot(x, w) + b
    return p